# dicjer run --name api-solid-pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker
# -e POSTGRESQL_DATABASE=apisolid -p 5432:5432 bitnami/postgressql

version: "3"

services:
  joanestech-hotelaria:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=joanestechnology
  joanestech-hotelaria-tst:
    image: bitnami/postgresql
    ports:
      - 5433:5433
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=joanestechnology-tst
